### DISCUSSION TITLE
Error: Unable to access jarfile /perf_test/perf-test.jar

### DISCUSSION THREAD

**Discussion by albionb96** [rabbitmq/rabbitmq-perf-test#564] [General]
So I don't know if I should open a bug report for this, but I thought I will start a discussion first.

I tried to start the latest client of the perf tool inside a pod in Kubernetes like below:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: perf-test
  name: perf-test
  namespace: message-broker
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: perf-test
        job-name: perf-test
    spec:
      containers:
      - name: rabbitmq-perf-test
        args:
        - --uri
        - amqp://user:pass@message-broker:5672
        - --quorum-queue
        - --rate
        - '1000'
        - --size
        - '1024'
        - --queue
        - queue-0
        - --producers
        - '1'
        - --consumers
        - '1'
        - --autoack
        - --metrics-prometheus
        - --queue-args
        - 'max-length-bytes=2000000000'
        image: pivotalrabbitmq/perf-test:2.19.0
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 300
```

And I got the following error:

`Error: Unable to access jarfile /perf_test/perf-test.jar`
